#!/usr/bin/env python3
"""Generate the Gazebo target-station models from the mission configuration.

One station model is produced per payload in ``mission.known_payloads``.  Each
contains:

* ``materials/textures/qr.png`` - the plate texture, rendered by the same
  ``mission_core.qr`` code the detector uses;
* ``meshes/plate.obj`` + ``plate.mtl`` - a unit quad with explicit UVs, so the
  texture mapping does not depend on how a renderer happens to UV-map a
  primitive box;
* ``model.sdf`` - a cube carrying the plate on its top and all four sides, on a
  short pedestal.

Generating rather than hand-writing these guarantees that the plate size in the
world and ``mission.qr_plate_size_m`` in the config can never drift apart -
and that drift would silently bias every PnP range estimate.

Usage::

    python scripts/generate_qr_targets.py
    python scripts/generate_qr_targets.py --config <path> --output <dir>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import cv2

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "ros2_ws" / "src" / "mission_core"))

from mission_core.config import load_mission_config  # noqa: E402
from mission_core.qr import (  # noqa: E402
    code_side_length_m,
    qr_module_count,
    render_qr_image,
)

DEFAULT_CONFIG = REPO_ROOT / "ros2_ws" / "src" / "mission_bringup" / "config" / "mission.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "ros2_ws" / "src" / "mission_bringup" / "models"

#: Height of the dark pedestal the coded cube sits on, in metres.
PEDESTAL_HEIGHT_M = 0.25
#: Pedestal footprint as a fraction of the cube edge.
PEDESTAL_FOOTPRINT_RATIO = 0.55

PLATE_OBJ = """# Unit plate for a QR target station.
# A 1x1 quad in the XY plane facing +Z, with explicit UVs so the texture
# mapping is identical in every renderer. Scaled to the plate size by the SDF.
#
# Winding: v1..v4 run counter-clockwise seen from +Z and UV (0,0) is the image
# bottom-left, so texture-right x texture-up == +normal and the code is NOT
# mirrored. A mirrored QR moves its third finder pattern to the bottom-right
# and is unreadable by OpenCV < 4.7.
mtllib plate.mtl
o qr_plate_{slug}
v -0.5 -0.5 0.0
v  0.5 -0.5 0.0
v  0.5  0.5 0.0
v -0.5  0.5 0.0
vt 0.0 0.0
vt 1.0 0.0
vt 1.0 1.0
vt 0.0 1.0
vn 0.0 0.0 1.0
usemtl {material}
f 1/1/1 2/2/1 3/3/1 4/4/1
"""

# The material name and the texture filename must both be unique per station.
# Ogre (and therefore gz-rendering) caches materials and textures by *name*, so
# three stations sharing "qr_material" / "qr.png" all end up displaying
# whichever one was loaded first - every station shows the same code, and the
# world model correctly but uselessly reports DUPLICATE_QR.
PLATE_MTL = """newmtl {material}
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
d 1.0
illum 1
map_Kd ../materials/textures/{texture}
"""

MODEL_CONFIG = """<?xml version="1.0"?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <author>
    <name>generated by scripts/generate_qr_targets.py</name>
  </author>
  <description>
    Mission target station carrying the unique QR payload {payload}.
    Plate side {plate:.3f} m, code side {code:.4f} m ({modules} modules,
    {quiet} module quiet zone).
  </description>
</model>
"""


def plate_visual(name: str, pose: str, plate_size: float, model_name: str) -> str:
    """One textured face of the station cube."""
    return f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry>
          <mesh>
            <uri>model://{model_name}/meshes/plate.obj</uri>
            <scale>{plate_size:.4f} {plate_size:.4f} 1</scale>
          </mesh>
        </geometry>
      </visual>
"""


def build_model_sdf(model_name: str, payload: str, plate_size: float) -> str:
    """SDF for one station: a coded cube on a pedestal, static."""
    half = plate_size / 2.0
    cube_centre_z = PEDESTAL_HEIGHT_M + half
    top_z = PEDESTAL_HEIGHT_M + plate_size
    pedestal_size = plate_size * PEDESTAL_FOOTPRINT_RATIO
    # The plate meshes are offset by 1 mm outside the collision cube so they do
    # not z-fight with it; the offset is far below the planner's grid
    # resolution and does not affect any measurement.
    epsilon = 0.001
    faces = (
        plate_visual("plate_top", f"0 0 {top_z + epsilon:.4f} 0 0 0", plate_size, model_name)
        + plate_visual(
            "plate_x_pos",
            f"{half + epsilon:.4f} 0 {cube_centre_z:.4f} 0 1.5707963 0",
            plate_size,
            model_name,
        )
        + plate_visual(
            "plate_x_neg",
            f"{-half - epsilon:.4f} 0 {cube_centre_z:.4f} 0 -1.5707963 0",
            plate_size,
            model_name,
        )
        + plate_visual(
            "plate_y_pos",
            f"0 {half + epsilon:.4f} {cube_centre_z:.4f} -1.5707963 0 0",
            plate_size,
            model_name,
        )
        + plate_visual(
            "plate_y_neg",
            f"0 {-half - epsilon:.4f} {cube_centre_z:.4f} 1.5707963 0 0",
            plate_size,
            model_name,
        )
    )
    return f"""<?xml version="1.0"?>
<!-- GENERATED by scripts/generate_qr_targets.py - do not edit by hand. -->
<sdf version="1.9">
  <model name="{model_name}">
    <static>true</static>
    <link name="body">
      <!-- Structural core of the station. White so the plate quiet zone
           blends into it if a face is ever viewed past the plate edge. -->
      <visual name="core">
        <pose>0 0 {cube_centre_z:.4f} 0 0 0</pose>
        <geometry>
          <box><size>{plate_size:.4f} {plate_size:.4f} {plate_size:.4f}</size></box>
        </geometry>
        <material>
          <ambient>0.9 0.9 0.9 1</ambient>
          <diffuse>0.95 0.95 0.95 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
        </material>
      </visual>
{faces}
      <visual name="pedestal">
        <pose>0 0 {PEDESTAL_HEIGHT_M / 2.0:.4f} 0 0 0</pose>
        <geometry>
          <box>
            <size>{pedestal_size:.4f} {pedestal_size:.4f} {PEDESTAL_HEIGHT_M:.4f}</size>
          </box>
        </geometry>
        <material>
          <ambient>0.15 0.15 0.18 1</ambient>
          <diffuse>0.20 0.20 0.24 1</diffuse>
        </material>
      </visual>

      <!-- The station is a real obstacle: the drone must map it from its camera and
           the planner must route the rover around it. -->
      <collision name="core_collision">
        <pose>0 0 {cube_centre_z:.4f} 0 0 0</pose>
        <geometry>
          <box><size>{plate_size:.4f} {plate_size:.4f} {plate_size:.4f}</size></box>
        </geometry>
      </collision>
      <collision name="pedestal_collision">
        <pose>0 0 {PEDESTAL_HEIGHT_M / 2.0:.4f} 0 0 0</pose>
        <geometry>
          <box>
            <size>{pedestal_size:.4f} {pedestal_size:.4f} {PEDESTAL_HEIGHT_M:.4f}</size>
          </box>
        </geometry>
      </collision>
    </link>
  </model>
</sdf>
"""


def generate(config_path: Path, output_dir: Path, texture_px: int) -> int:
    config = load_mission_config(config_path)
    plate_size = config.mission.qr_plate_size_m
    quiet = config.mission.qr_quiet_zone_modules

    for payload in config.mission.known_payloads:
        model_name = f"target_station_{payload.lower()}"
        model_dir = output_dir / model_name
        (model_dir / "meshes").mkdir(parents=True, exist_ok=True)
        (model_dir / "materials" / "textures").mkdir(parents=True, exist_ok=True)

        slug = payload.lower()
        material = f"qr_material_{slug}"
        texture_name = f"qr_{slug}.png"

        texture = render_qr_image(payload, texture_px, quiet)
        texture_path = model_dir / "materials" / "textures" / texture_name
        if not cv2.imwrite(str(texture_path), texture):
            raise RuntimeError(f"failed to write {texture_path}")

        (model_dir / "meshes" / "plate.obj").write_text(
            PLATE_OBJ.format(slug=slug, material=material), encoding="utf-8"
        )
        (model_dir / "meshes" / "plate.mtl").write_text(
            PLATE_MTL.format(material=material, texture=texture_name), encoding="utf-8"
        )
        (model_dir / "model.sdf").write_text(
            build_model_sdf(model_name, payload, plate_size), encoding="utf-8"
        )
        modules = qr_module_count(payload)
        code = code_side_length_m(payload, plate_size, quiet)
        (model_dir / "model.config").write_text(
            MODEL_CONFIG.format(
                model_name=model_name,
                payload=payload,
                plate=plate_size,
                code=code,
                modules=modules,
                quiet=quiet,
            ),
            encoding="utf-8",
        )
        print(
            f"{model_name:26s} payload={payload:9s} texture={texture.shape[0]}px "
            f"modules={modules} code_side={code:.4f} m "
            f"({code / plate_size:.4f} of the {plate_size:.2f} m plate) "
            f"material={material}"
        )

    print(f"\nwrote {len(config.mission.known_payloads)} station models to {output_dir}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--texture-px",
        type=int,
        default=1024,
        help="approximate texture edge in pixels (rounded to a whole number of modules)",
    )
    args = parser.parse_args()
    return generate(args.config, args.output, args.texture_px)


if __name__ == "__main__":
    raise SystemExit(main())
